name: "Run test on main merge"

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Run test on main merge'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
        name: Install dependencies
      - run: npm run test
        name: Run headless tests
